# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ladis/Projects/Quantum

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ladis/Projects/Quantum

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/local/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Data\" \"Documentation\" \"Header\" \"Other\" \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /home/ladis/Projects/Quantum && /usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /home/ladis/Projects/Quantum && /usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/ladis/Projects/Quantum/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/ladis/Projects/Quantum && $(CMAKE_COMMAND) -E cmake_progress_start /home/ladis/Projects/Quantum/CMakeFiles /home/ladis/Projects/Quantum/src/lib/Quantum-Engine/CMakeFiles/progress.marks
	cd /home/ladis/Projects/Quantum && $(MAKE) -f CMakeFiles/Makefile2 src/lib/Quantum-Engine/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ladis/Projects/Quantum/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f CMakeFiles/Makefile2 src/lib/Quantum-Engine/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/ladis/Projects/Quantum && $(MAKE) -f CMakeFiles/Makefile2 src/lib/Quantum-Engine/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f CMakeFiles/Makefile2 src/lib/Quantum-Engine/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/ladis/Projects/Quantum && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/rule:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f CMakeFiles/Makefile2 src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/rule
.PHONY : src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/rule

# Convenience name for target.
QuantumEngine: src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/rule
.PHONY : QuantumEngine

# fast build rule for target.
QuantumEngine/fast:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build
.PHONY : QuantumEngine/fast

src/engine/AnimatedSprite.o: src/engine/AnimatedSprite.cpp.o
.PHONY : src/engine/AnimatedSprite.o

# target to build an object file
src/engine/AnimatedSprite.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/AnimatedSprite.cpp.o
.PHONY : src/engine/AnimatedSprite.cpp.o

src/engine/AnimatedSprite.i: src/engine/AnimatedSprite.cpp.i
.PHONY : src/engine/AnimatedSprite.i

# target to preprocess a source file
src/engine/AnimatedSprite.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/AnimatedSprite.cpp.i
.PHONY : src/engine/AnimatedSprite.cpp.i

src/engine/AnimatedSprite.s: src/engine/AnimatedSprite.cpp.s
.PHONY : src/engine/AnimatedSprite.s

# target to generate assembly for a file
src/engine/AnimatedSprite.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/AnimatedSprite.cpp.s
.PHONY : src/engine/AnimatedSprite.cpp.s

src/engine/Color.o: src/engine/Color.cpp.o
.PHONY : src/engine/Color.o

# target to build an object file
src/engine/Color.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Color.cpp.o
.PHONY : src/engine/Color.cpp.o

src/engine/Color.i: src/engine/Color.cpp.i
.PHONY : src/engine/Color.i

# target to preprocess a source file
src/engine/Color.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Color.cpp.i
.PHONY : src/engine/Color.cpp.i

src/engine/Color.s: src/engine/Color.cpp.s
.PHONY : src/engine/Color.s

# target to generate assembly for a file
src/engine/Color.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Color.cpp.s
.PHONY : src/engine/Color.cpp.s

src/engine/EventListener.o: src/engine/EventListener.cpp.o
.PHONY : src/engine/EventListener.o

# target to build an object file
src/engine/EventListener.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/EventListener.cpp.o
.PHONY : src/engine/EventListener.cpp.o

src/engine/EventListener.i: src/engine/EventListener.cpp.i
.PHONY : src/engine/EventListener.i

# target to preprocess a source file
src/engine/EventListener.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/EventListener.cpp.i
.PHONY : src/engine/EventListener.cpp.i

src/engine/EventListener.s: src/engine/EventListener.cpp.s
.PHONY : src/engine/EventListener.s

# target to generate assembly for a file
src/engine/EventListener.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/EventListener.cpp.s
.PHONY : src/engine/EventListener.cpp.s

src/engine/Game.o: src/engine/Game.cpp.o
.PHONY : src/engine/Game.o

# target to build an object file
src/engine/Game.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game.cpp.o
.PHONY : src/engine/Game.cpp.o

src/engine/Game.i: src/engine/Game.cpp.i
.PHONY : src/engine/Game.i

# target to preprocess a source file
src/engine/Game.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game.cpp.i
.PHONY : src/engine/Game.cpp.i

src/engine/Game.s: src/engine/Game.cpp.s
.PHONY : src/engine/Game.s

# target to generate assembly for a file
src/engine/Game.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game.cpp.s
.PHONY : src/engine/Game.cpp.s

src/engine/Game2D.o: src/engine/Game2D.cpp.o
.PHONY : src/engine/Game2D.o

# target to build an object file
src/engine/Game2D.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game2D.cpp.o
.PHONY : src/engine/Game2D.cpp.o

src/engine/Game2D.i: src/engine/Game2D.cpp.i
.PHONY : src/engine/Game2D.i

# target to preprocess a source file
src/engine/Game2D.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game2D.cpp.i
.PHONY : src/engine/Game2D.cpp.i

src/engine/Game2D.s: src/engine/Game2D.cpp.s
.PHONY : src/engine/Game2D.s

# target to generate assembly for a file
src/engine/Game2D.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game2D.cpp.s
.PHONY : src/engine/Game2D.cpp.s

src/engine/Game3D.o: src/engine/Game3D.cpp.o
.PHONY : src/engine/Game3D.o

# target to build an object file
src/engine/Game3D.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game3D.cpp.o
.PHONY : src/engine/Game3D.cpp.o

src/engine/Game3D.i: src/engine/Game3D.cpp.i
.PHONY : src/engine/Game3D.i

# target to preprocess a source file
src/engine/Game3D.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game3D.cpp.i
.PHONY : src/engine/Game3D.cpp.i

src/engine/Game3D.s: src/engine/Game3D.cpp.s
.PHONY : src/engine/Game3D.s

# target to generate assembly for a file
src/engine/Game3D.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Game3D.cpp.s
.PHONY : src/engine/Game3D.cpp.s

src/engine/GameObject.o: src/engine/GameObject.cpp.o
.PHONY : src/engine/GameObject.o

# target to build an object file
src/engine/GameObject.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/GameObject.cpp.o
.PHONY : src/engine/GameObject.cpp.o

src/engine/GameObject.i: src/engine/GameObject.cpp.i
.PHONY : src/engine/GameObject.i

# target to preprocess a source file
src/engine/GameObject.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/GameObject.cpp.i
.PHONY : src/engine/GameObject.cpp.i

src/engine/GameObject.s: src/engine/GameObject.cpp.s
.PHONY : src/engine/GameObject.s

# target to generate assembly for a file
src/engine/GameObject.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/GameObject.cpp.s
.PHONY : src/engine/GameObject.cpp.s

src/engine/Math.o: src/engine/Math.cpp.o
.PHONY : src/engine/Math.o

# target to build an object file
src/engine/Math.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Math.cpp.o
.PHONY : src/engine/Math.cpp.o

src/engine/Math.i: src/engine/Math.cpp.i
.PHONY : src/engine/Math.i

# target to preprocess a source file
src/engine/Math.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Math.cpp.i
.PHONY : src/engine/Math.cpp.i

src/engine/Math.s: src/engine/Math.cpp.s
.PHONY : src/engine/Math.s

# target to generate assembly for a file
src/engine/Math.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Math.cpp.s
.PHONY : src/engine/Math.cpp.s

src/engine/ParallaxScrolling.o: src/engine/ParallaxScrolling.cpp.o
.PHONY : src/engine/ParallaxScrolling.o

# target to build an object file
src/engine/ParallaxScrolling.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/ParallaxScrolling.cpp.o
.PHONY : src/engine/ParallaxScrolling.cpp.o

src/engine/ParallaxScrolling.i: src/engine/ParallaxScrolling.cpp.i
.PHONY : src/engine/ParallaxScrolling.i

# target to preprocess a source file
src/engine/ParallaxScrolling.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/ParallaxScrolling.cpp.i
.PHONY : src/engine/ParallaxScrolling.cpp.i

src/engine/ParallaxScrolling.s: src/engine/ParallaxScrolling.cpp.s
.PHONY : src/engine/ParallaxScrolling.s

# target to generate assembly for a file
src/engine/ParallaxScrolling.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/ParallaxScrolling.cpp.s
.PHONY : src/engine/ParallaxScrolling.cpp.s

src/engine/RenderizableAsset.o: src/engine/RenderizableAsset.cpp.o
.PHONY : src/engine/RenderizableAsset.o

# target to build an object file
src/engine/RenderizableAsset.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/RenderizableAsset.cpp.o
.PHONY : src/engine/RenderizableAsset.cpp.o

src/engine/RenderizableAsset.i: src/engine/RenderizableAsset.cpp.i
.PHONY : src/engine/RenderizableAsset.i

# target to preprocess a source file
src/engine/RenderizableAsset.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/RenderizableAsset.cpp.i
.PHONY : src/engine/RenderizableAsset.cpp.i

src/engine/RenderizableAsset.s: src/engine/RenderizableAsset.cpp.s
.PHONY : src/engine/RenderizableAsset.s

# target to generate assembly for a file
src/engine/RenderizableAsset.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/RenderizableAsset.cpp.s
.PHONY : src/engine/RenderizableAsset.cpp.s

src/engine/ResourceManager.o: src/engine/ResourceManager.cpp.o
.PHONY : src/engine/ResourceManager.o

# target to build an object file
src/engine/ResourceManager.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/ResourceManager.cpp.o
.PHONY : src/engine/ResourceManager.cpp.o

src/engine/ResourceManager.i: src/engine/ResourceManager.cpp.i
.PHONY : src/engine/ResourceManager.i

# target to preprocess a source file
src/engine/ResourceManager.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/ResourceManager.cpp.i
.PHONY : src/engine/ResourceManager.cpp.i

src/engine/ResourceManager.s: src/engine/ResourceManager.cpp.s
.PHONY : src/engine/ResourceManager.s

# target to generate assembly for a file
src/engine/ResourceManager.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/ResourceManager.cpp.s
.PHONY : src/engine/ResourceManager.cpp.s

src/engine/Scene.o: src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.o

# target to build an object file
src/engine/Scene.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.cpp.o

src/engine/Scene.i: src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.i

# target to preprocess a source file
src/engine/Scene.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.cpp.i

src/engine/Scene.s: src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.s

# target to generate assembly for a file
src/engine/Scene.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.cpp.s

src/engine/SceneManager.o: src/engine/SceneManager.cpp.o
.PHONY : src/engine/SceneManager.o

# target to build an object file
src/engine/SceneManager.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/SceneManager.cpp.o
.PHONY : src/engine/SceneManager.cpp.o

src/engine/SceneManager.i: src/engine/SceneManager.cpp.i
.PHONY : src/engine/SceneManager.i

# target to preprocess a source file
src/engine/SceneManager.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/SceneManager.cpp.i
.PHONY : src/engine/SceneManager.cpp.i

src/engine/SceneManager.s: src/engine/SceneManager.cpp.s
.PHONY : src/engine/SceneManager.s

# target to generate assembly for a file
src/engine/SceneManager.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/SceneManager.cpp.s
.PHONY : src/engine/SceneManager.cpp.s

src/engine/Sprite.o: src/engine/Sprite.cpp.o
.PHONY : src/engine/Sprite.o

# target to build an object file
src/engine/Sprite.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Sprite.cpp.o
.PHONY : src/engine/Sprite.cpp.o

src/engine/Sprite.i: src/engine/Sprite.cpp.i
.PHONY : src/engine/Sprite.i

# target to preprocess a source file
src/engine/Sprite.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Sprite.cpp.i
.PHONY : src/engine/Sprite.cpp.i

src/engine/Sprite.s: src/engine/Sprite.cpp.s
.PHONY : src/engine/Sprite.s

# target to generate assembly for a file
src/engine/Sprite.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Sprite.cpp.s
.PHONY : src/engine/Sprite.cpp.s

src/engine/SpriteSheetAnimation.o: src/engine/SpriteSheetAnimation.cpp.o
.PHONY : src/engine/SpriteSheetAnimation.o

# target to build an object file
src/engine/SpriteSheetAnimation.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/SpriteSheetAnimation.cpp.o
.PHONY : src/engine/SpriteSheetAnimation.cpp.o

src/engine/SpriteSheetAnimation.i: src/engine/SpriteSheetAnimation.cpp.i
.PHONY : src/engine/SpriteSheetAnimation.i

# target to preprocess a source file
src/engine/SpriteSheetAnimation.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/SpriteSheetAnimation.cpp.i
.PHONY : src/engine/SpriteSheetAnimation.cpp.i

src/engine/SpriteSheetAnimation.s: src/engine/SpriteSheetAnimation.cpp.s
.PHONY : src/engine/SpriteSheetAnimation.s

# target to generate assembly for a file
src/engine/SpriteSheetAnimation.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/SpriteSheetAnimation.cpp.s
.PHONY : src/engine/SpriteSheetAnimation.cpp.s

src/engine/Vector2.o: src/engine/Vector2.cpp.o
.PHONY : src/engine/Vector2.o

# target to build an object file
src/engine/Vector2.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Vector2.cpp.o
.PHONY : src/engine/Vector2.cpp.o

src/engine/Vector2.i: src/engine/Vector2.cpp.i
.PHONY : src/engine/Vector2.i

# target to preprocess a source file
src/engine/Vector2.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Vector2.cpp.i
.PHONY : src/engine/Vector2.cpp.i

src/engine/Vector2.s: src/engine/Vector2.cpp.s
.PHONY : src/engine/Vector2.s

# target to generate assembly for a file
src/engine/Vector2.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Vector2.cpp.s
.PHONY : src/engine/Vector2.cpp.s

src/engine/Vector3.o: src/engine/Vector3.cpp.o
.PHONY : src/engine/Vector3.o

# target to build an object file
src/engine/Vector3.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Vector3.cpp.o
.PHONY : src/engine/Vector3.cpp.o

src/engine/Vector3.i: src/engine/Vector3.cpp.i
.PHONY : src/engine/Vector3.i

# target to preprocess a source file
src/engine/Vector3.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Vector3.cpp.i
.PHONY : src/engine/Vector3.cpp.i

src/engine/Vector3.s: src/engine/Vector3.cpp.s
.PHONY : src/engine/Vector3.s

# target to generate assembly for a file
src/engine/Vector3.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Vector3.cpp.s
.PHONY : src/engine/Vector3.cpp.s

src/engine/Window.o: src/engine/Window.cpp.o
.PHONY : src/engine/Window.o

# target to build an object file
src/engine/Window.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Window.cpp.o
.PHONY : src/engine/Window.cpp.o

src/engine/Window.i: src/engine/Window.cpp.i
.PHONY : src/engine/Window.i

# target to preprocess a source file
src/engine/Window.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Window.cpp.i
.PHONY : src/engine/Window.cpp.i

src/engine/Window.s: src/engine/Window.cpp.s
.PHONY : src/engine/Window.s

# target to generate assembly for a file
src/engine/Window.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/Window.cpp.s
.PHONY : src/engine/Window.cpp.s

src/engine/components/2D/AssetRenderer.o: src/engine/components/2D/AssetRenderer.cpp.o
.PHONY : src/engine/components/2D/AssetRenderer.o

# target to build an object file
src/engine/components/2D/AssetRenderer.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/AssetRenderer.cpp.o
.PHONY : src/engine/components/2D/AssetRenderer.cpp.o

src/engine/components/2D/AssetRenderer.i: src/engine/components/2D/AssetRenderer.cpp.i
.PHONY : src/engine/components/2D/AssetRenderer.i

# target to preprocess a source file
src/engine/components/2D/AssetRenderer.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/AssetRenderer.cpp.i
.PHONY : src/engine/components/2D/AssetRenderer.cpp.i

src/engine/components/2D/AssetRenderer.s: src/engine/components/2D/AssetRenderer.cpp.s
.PHONY : src/engine/components/2D/AssetRenderer.s

# target to generate assembly for a file
src/engine/components/2D/AssetRenderer.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/AssetRenderer.cpp.s
.PHONY : src/engine/components/2D/AssetRenderer.cpp.s

src/engine/components/2D/BoxCollider.o: src/engine/components/2D/BoxCollider.cpp.o
.PHONY : src/engine/components/2D/BoxCollider.o

# target to build an object file
src/engine/components/2D/BoxCollider.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/BoxCollider.cpp.o
.PHONY : src/engine/components/2D/BoxCollider.cpp.o

src/engine/components/2D/BoxCollider.i: src/engine/components/2D/BoxCollider.cpp.i
.PHONY : src/engine/components/2D/BoxCollider.i

# target to preprocess a source file
src/engine/components/2D/BoxCollider.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/BoxCollider.cpp.i
.PHONY : src/engine/components/2D/BoxCollider.cpp.i

src/engine/components/2D/BoxCollider.s: src/engine/components/2D/BoxCollider.cpp.s
.PHONY : src/engine/components/2D/BoxCollider.s

# target to generate assembly for a file
src/engine/components/2D/BoxCollider.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/BoxCollider.cpp.s
.PHONY : src/engine/components/2D/BoxCollider.cpp.s

src/engine/components/2D/Camera.o: src/engine/components/2D/Camera.cpp.o
.PHONY : src/engine/components/2D/Camera.o

# target to build an object file
src/engine/components/2D/Camera.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Camera.cpp.o
.PHONY : src/engine/components/2D/Camera.cpp.o

src/engine/components/2D/Camera.i: src/engine/components/2D/Camera.cpp.i
.PHONY : src/engine/components/2D/Camera.i

# target to preprocess a source file
src/engine/components/2D/Camera.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Camera.cpp.i
.PHONY : src/engine/components/2D/Camera.cpp.i

src/engine/components/2D/Camera.s: src/engine/components/2D/Camera.cpp.s
.PHONY : src/engine/components/2D/Camera.s

# target to generate assembly for a file
src/engine/components/2D/Camera.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Camera.cpp.s
.PHONY : src/engine/components/2D/Camera.cpp.s

src/engine/components/2D/CircleCollider.o: src/engine/components/2D/CircleCollider.cpp.o
.PHONY : src/engine/components/2D/CircleCollider.o

# target to build an object file
src/engine/components/2D/CircleCollider.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/CircleCollider.cpp.o
.PHONY : src/engine/components/2D/CircleCollider.cpp.o

src/engine/components/2D/CircleCollider.i: src/engine/components/2D/CircleCollider.cpp.i
.PHONY : src/engine/components/2D/CircleCollider.i

# target to preprocess a source file
src/engine/components/2D/CircleCollider.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/CircleCollider.cpp.i
.PHONY : src/engine/components/2D/CircleCollider.cpp.i

src/engine/components/2D/CircleCollider.s: src/engine/components/2D/CircleCollider.cpp.s
.PHONY : src/engine/components/2D/CircleCollider.s

# target to generate assembly for a file
src/engine/components/2D/CircleCollider.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/CircleCollider.cpp.s
.PHONY : src/engine/components/2D/CircleCollider.cpp.s

src/engine/components/2D/Physics.o: src/engine/components/2D/Physics.cpp.o
.PHONY : src/engine/components/2D/Physics.o

# target to build an object file
src/engine/components/2D/Physics.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Physics.cpp.o
.PHONY : src/engine/components/2D/Physics.cpp.o

src/engine/components/2D/Physics.i: src/engine/components/2D/Physics.cpp.i
.PHONY : src/engine/components/2D/Physics.i

# target to preprocess a source file
src/engine/components/2D/Physics.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Physics.cpp.i
.PHONY : src/engine/components/2D/Physics.cpp.i

src/engine/components/2D/Physics.s: src/engine/components/2D/Physics.cpp.s
.PHONY : src/engine/components/2D/Physics.s

# target to generate assembly for a file
src/engine/components/2D/Physics.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Physics.cpp.s
.PHONY : src/engine/components/2D/Physics.cpp.s

src/engine/components/2D/Transform2D.o: src/engine/components/2D/Transform2D.cpp.o
.PHONY : src/engine/components/2D/Transform2D.o

# target to build an object file
src/engine/components/2D/Transform2D.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Transform2D.cpp.o
.PHONY : src/engine/components/2D/Transform2D.cpp.o

src/engine/components/2D/Transform2D.i: src/engine/components/2D/Transform2D.cpp.i
.PHONY : src/engine/components/2D/Transform2D.i

# target to preprocess a source file
src/engine/components/2D/Transform2D.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Transform2D.cpp.i
.PHONY : src/engine/components/2D/Transform2D.cpp.i

src/engine/components/2D/Transform2D.s: src/engine/components/2D/Transform2D.cpp.s
.PHONY : src/engine/components/2D/Transform2D.s

# target to generate assembly for a file
src/engine/components/2D/Transform2D.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/2D/Transform2D.cpp.s
.PHONY : src/engine/components/2D/Transform2D.cpp.s

src/engine/components/Component.o: src/engine/components/Component.cpp.o
.PHONY : src/engine/components/Component.o

# target to build an object file
src/engine/components/Component.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/Component.cpp.o
.PHONY : src/engine/components/Component.cpp.o

src/engine/components/Component.i: src/engine/components/Component.cpp.i
.PHONY : src/engine/components/Component.i

# target to preprocess a source file
src/engine/components/Component.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/Component.cpp.i
.PHONY : src/engine/components/Component.cpp.i

src/engine/components/Component.s: src/engine/components/Component.cpp.s
.PHONY : src/engine/components/Component.s

# target to generate assembly for a file
src/engine/components/Component.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/components/Component.cpp.s
.PHONY : src/engine/components/Component.cpp.s

src/engine/systems/2D/AssetRendering.o: src/engine/systems/2D/AssetRendering.cpp.o
.PHONY : src/engine/systems/2D/AssetRendering.o

# target to build an object file
src/engine/systems/2D/AssetRendering.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/AssetRendering.cpp.o
.PHONY : src/engine/systems/2D/AssetRendering.cpp.o

src/engine/systems/2D/AssetRendering.i: src/engine/systems/2D/AssetRendering.cpp.i
.PHONY : src/engine/systems/2D/AssetRendering.i

# target to preprocess a source file
src/engine/systems/2D/AssetRendering.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/AssetRendering.cpp.i
.PHONY : src/engine/systems/2D/AssetRendering.cpp.i

src/engine/systems/2D/AssetRendering.s: src/engine/systems/2D/AssetRendering.cpp.s
.PHONY : src/engine/systems/2D/AssetRendering.s

# target to generate assembly for a file
src/engine/systems/2D/AssetRendering.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/AssetRendering.cpp.s
.PHONY : src/engine/systems/2D/AssetRendering.cpp.s

src/engine/systems/2D/Collisions.o: src/engine/systems/2D/Collisions.cpp.o
.PHONY : src/engine/systems/2D/Collisions.o

# target to build an object file
src/engine/systems/2D/Collisions.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/Collisions.cpp.o
.PHONY : src/engine/systems/2D/Collisions.cpp.o

src/engine/systems/2D/Collisions.i: src/engine/systems/2D/Collisions.cpp.i
.PHONY : src/engine/systems/2D/Collisions.i

# target to preprocess a source file
src/engine/systems/2D/Collisions.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/Collisions.cpp.i
.PHONY : src/engine/systems/2D/Collisions.cpp.i

src/engine/systems/2D/Collisions.s: src/engine/systems/2D/Collisions.cpp.s
.PHONY : src/engine/systems/2D/Collisions.s

# target to generate assembly for a file
src/engine/systems/2D/Collisions.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/Collisions.cpp.s
.PHONY : src/engine/systems/2D/Collisions.cpp.s

src/engine/systems/2D/Physics.o: src/engine/systems/2D/Physics.cpp.o
.PHONY : src/engine/systems/2D/Physics.o

# target to build an object file
src/engine/systems/2D/Physics.cpp.o:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/Physics.cpp.o
.PHONY : src/engine/systems/2D/Physics.cpp.o

src/engine/systems/2D/Physics.i: src/engine/systems/2D/Physics.cpp.i
.PHONY : src/engine/systems/2D/Physics.i

# target to preprocess a source file
src/engine/systems/2D/Physics.cpp.i:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/Physics.cpp.i
.PHONY : src/engine/systems/2D/Physics.cpp.i

src/engine/systems/2D/Physics.s: src/engine/systems/2D/Physics.cpp.s
.PHONY : src/engine/systems/2D/Physics.s

# target to generate assembly for a file
src/engine/systems/2D/Physics.cpp.s:
	cd /home/ladis/Projects/Quantum && $(MAKE) -f src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/build.make src/lib/Quantum-Engine/CMakeFiles/QuantumEngine.dir/src/engine/systems/2D/Physics.cpp.s
.PHONY : src/engine/systems/2D/Physics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... QuantumEngine"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... src/engine/AnimatedSprite.o"
	@echo "... src/engine/AnimatedSprite.i"
	@echo "... src/engine/AnimatedSprite.s"
	@echo "... src/engine/Color.o"
	@echo "... src/engine/Color.i"
	@echo "... src/engine/Color.s"
	@echo "... src/engine/EventListener.o"
	@echo "... src/engine/EventListener.i"
	@echo "... src/engine/EventListener.s"
	@echo "... src/engine/Game.o"
	@echo "... src/engine/Game.i"
	@echo "... src/engine/Game.s"
	@echo "... src/engine/Game2D.o"
	@echo "... src/engine/Game2D.i"
	@echo "... src/engine/Game2D.s"
	@echo "... src/engine/Game3D.o"
	@echo "... src/engine/Game3D.i"
	@echo "... src/engine/Game3D.s"
	@echo "... src/engine/GameObject.o"
	@echo "... src/engine/GameObject.i"
	@echo "... src/engine/GameObject.s"
	@echo "... src/engine/Math.o"
	@echo "... src/engine/Math.i"
	@echo "... src/engine/Math.s"
	@echo "... src/engine/ParallaxScrolling.o"
	@echo "... src/engine/ParallaxScrolling.i"
	@echo "... src/engine/ParallaxScrolling.s"
	@echo "... src/engine/RenderizableAsset.o"
	@echo "... src/engine/RenderizableAsset.i"
	@echo "... src/engine/RenderizableAsset.s"
	@echo "... src/engine/ResourceManager.o"
	@echo "... src/engine/ResourceManager.i"
	@echo "... src/engine/ResourceManager.s"
	@echo "... src/engine/Scene.o"
	@echo "... src/engine/Scene.i"
	@echo "... src/engine/Scene.s"
	@echo "... src/engine/SceneManager.o"
	@echo "... src/engine/SceneManager.i"
	@echo "... src/engine/SceneManager.s"
	@echo "... src/engine/Sprite.o"
	@echo "... src/engine/Sprite.i"
	@echo "... src/engine/Sprite.s"
	@echo "... src/engine/SpriteSheetAnimation.o"
	@echo "... src/engine/SpriteSheetAnimation.i"
	@echo "... src/engine/SpriteSheetAnimation.s"
	@echo "... src/engine/Vector2.o"
	@echo "... src/engine/Vector2.i"
	@echo "... src/engine/Vector2.s"
	@echo "... src/engine/Vector3.o"
	@echo "... src/engine/Vector3.i"
	@echo "... src/engine/Vector3.s"
	@echo "... src/engine/Window.o"
	@echo "... src/engine/Window.i"
	@echo "... src/engine/Window.s"
	@echo "... src/engine/components/2D/AssetRenderer.o"
	@echo "... src/engine/components/2D/AssetRenderer.i"
	@echo "... src/engine/components/2D/AssetRenderer.s"
	@echo "... src/engine/components/2D/BoxCollider.o"
	@echo "... src/engine/components/2D/BoxCollider.i"
	@echo "... src/engine/components/2D/BoxCollider.s"
	@echo "... src/engine/components/2D/Camera.o"
	@echo "... src/engine/components/2D/Camera.i"
	@echo "... src/engine/components/2D/Camera.s"
	@echo "... src/engine/components/2D/CircleCollider.o"
	@echo "... src/engine/components/2D/CircleCollider.i"
	@echo "... src/engine/components/2D/CircleCollider.s"
	@echo "... src/engine/components/2D/Physics.o"
	@echo "... src/engine/components/2D/Physics.i"
	@echo "... src/engine/components/2D/Physics.s"
	@echo "... src/engine/components/2D/Transform2D.o"
	@echo "... src/engine/components/2D/Transform2D.i"
	@echo "... src/engine/components/2D/Transform2D.s"
	@echo "... src/engine/components/Component.o"
	@echo "... src/engine/components/Component.i"
	@echo "... src/engine/components/Component.s"
	@echo "... src/engine/systems/2D/AssetRendering.o"
	@echo "... src/engine/systems/2D/AssetRendering.i"
	@echo "... src/engine/systems/2D/AssetRendering.s"
	@echo "... src/engine/systems/2D/Collisions.o"
	@echo "... src/engine/systems/2D/Collisions.i"
	@echo "... src/engine/systems/2D/Collisions.s"
	@echo "... src/engine/systems/2D/Physics.o"
	@echo "... src/engine/systems/2D/Physics.i"
	@echo "... src/engine/systems/2D/Physics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/ladis/Projects/Quantum && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

